# The Hermes memory provider that makes the shared agent-memory knowledge
# graph (home/agent-memory.nix) Hermes's persistent memory.
#
# Why a provider and not just the MCP row: an MCP server hands Hermes tools
# and nothing more, so the graph is consulted only when the model decides to
# search -- while the native memory this replaces (MEMORY.md/USER.md, off in
# home/hermes.nix) is loaded into every session and reviewed on a ten-turn
# cadence. `memory.provider` is the hook that gets that behaviour back:
# Hermes' MemoryManager calls prefetch() before every turn, so recall no
# longer depends on the model deciding to look, and the provider's own review
# note stands in for the native ten-turn review, whose nudge is gated on the
# native store and so out of reach for a provider.
#
# Recall-only, deliberately. The provider publishes no tools and never
# writes: every write stays on the mcp__memory__* tools the agent already
# has, which keeps the graph's single-writer design intact (mcp-proxy owns
# the JSONL file and the reference server takes no cross-process lock).
#
# Packaging: an installed Python package carrying a
# `hermes_agent.memory_providers` entry point, upstream's documented route
# for out-of-tree providers. It rides `extraPythonPackages` rather than the
# `extraPlugins` symlink route because a directory plugin is discovered under
# its `nix-managed-` symlink name and `memory.provider` has to name the
# provider: the entry-point name is `agent-memory`. The graph URL, the server
# name and the cadence are interpolated from home/agent-memory.nix so the
# plugin cannot drift from the server it talks to.
{
  pkgs,
  # home/agent-memory.nix -- the one definition of the server, its name, its
  # port and its store.
  agentMemory,
  # User turns between review notes; mirrors the native nudge
  # (memory.nudge_interval, default 10).
  nudgeTurns ? 10,
}:

let
  providerName = "agent-memory";

  providerModule = pkgs.writeTextFile {
    name = "hermes-agent-memory-provider.py";
    text = ''
      """Hermes memory provider: the shared agent-memory knowledge graph.

      Recall-only by design. Hermes asks this provider for context before each
      turn; it searches the graph -- the same JSONL store every harness on this
      machine reads and writes, served over loopback Streamable HTTP by mcp-proxy
      -- and returns the matching entities. Every NUDGE_TURNS user turns it also
      asks the agent to review the session for durable facts and save them. It
      publishes no tools and never writes: the write path stays the
      mcp__<server>__* MCP tools the agent already has, which keeps the graph's
      single-writer design (the proxy owns the file) intact.

      The module is generated by home/hermes-agent-memory.nix: GRAPH_URL,
      SERVER_NAME and NUDGE_TURNS are interpolated at build time so they cannot
      drift from home/agent-memory.nix (the one definition of the server, its
      name and its port).
      """

      from __future__ import annotations

      import asyncio
      import json
      import logging
      import re
      import threading
      from typing import Any, Dict, List, Optional, Sequence, Tuple

      from agent.memory_provider import MemoryProvider, RecallStatus

      logger = logging.getLogger("hermes.memory.agent-memory")

      # -- Build-time constants ---------------------------------------------------
      GRAPH_URL = "${agentMemory.url}"
      SERVER_NAME = "${agentMemory.name}"
      NUDGE_TURNS = int("${toString nudgeTurns}")

      # -- Recall shape -----------------------------------------------------------
      # search_nodes is substring matching over entity names, types and
      # observations, so a whole user message rarely matches anything; split it
      # into a few distinctive terms and union the hits instead. Everything is
      # capped, because the block is stamped into the turn and replayed on every
      # later request while that turn stays in context.
      MAX_TERMS = 4
      MAX_ENTITIES = 3
      MAX_OBSERVATIONS = 2
      OBSERVATION_CHARS = 220
      RECALL_CHARS = 1400
      # prefetch() runs on the turn's critical path (before the request), so a
      # cache miss gets a short leash; queue_prefetch() rides the manager's
      # background worker, where the full search fits.
      PREFETCH_TIMEOUT_S = 1.5
      BACKGROUND_TIMEOUT_S = 6.0

      TOOL_PREFIX = "mcp__" + SERVER_NAME + "__"

      # The review note. Hermes's native memory nudges a review every ten turns by
      # forking a background agent; a memory provider gets no such hook (the gate
      # is on the native store), so the equivalent rides the same prefetch channel
      # as the recall itself -- one short standing task, once per cadence.
      REVIEW_NOTE = (
          f"[{SERVER_NAME} review due -- standing task: after answering the user, review this "
          f"session for durable facts (decisions, preferences, conventions, environment facts, "
          f"project state) and save what future sessions will want, with "
          f"{TOOL_PREFIX}search_nodes, {TOOL_PREFIX}add_observations, {TOOL_PREFIX}create_entities "
          f"and {TOOL_PREFIX}create_relations. Search before writing; prefer add_observations on "
          f"an existing entity over a near-duplicate; keep entries declarative and specific; skip "
          f"transient chatter.]"
      )

      _STOPWORDS = frozenset(
          """
      a about above after again against all also am an and any are around as at back be because
      been before being below between both but by came can cannot come could did do does doing
      down during each few for from further get give go going had has have having he help her
      here hers him his how i if in into is it its itself just know like look made make many
      may me might more most much must my need no nor not now of off on once one only or other
      our out over own please really said same say see she should since so some still such sure
      take than that the their them then there these they thing things think this those through
      time to too under until up us use used very want was way we well were what when where
      which while who whom why will with would yeah you your yours
      """.split()
      )

      # A candidate term: at least four characters, starting with a letter, so file
      # extensions, numbers and shell flags do not become search keys.
      _WORD_RE = re.compile(r"[A-Za-z][A-Za-z0-9_+.\-]{3,}")


      def _search_terms(text: str) -> List[str]:
          """Distinctive lowercase terms from a user message, longest first, in message order."""
          words: List[str] = []
          seen: set = set()
          for raw in _WORD_RE.findall(text or ""):
              word = raw.strip("._+-").lower()
              if len(word) < 4 or word in _STOPWORDS or word in seen:
                  continue
              seen.add(word)
              words.append(word)
          if len(words) <= MAX_TERMS:
              return words
          keep = set(sorted(words, key=len, reverse=True)[:MAX_TERMS])
          return [word for word in words if word in keep]


      def _format_recall(entities: Sequence[Dict[str, Any]]) -> Tuple[str, int]:
          """Render matching entities as a compact bullet block; return (text, entity count)."""
          lines: List[str] = []
          used = 0
          for entity in entities:
              if len(lines) >= MAX_ENTITIES:
                  break
              name = str(entity.get("name") or "").strip()
              kind = str(entity.get("entityType") or entity.get("entity_type") or "").strip()
              observations = [
                  item for item in (entity.get("observations") or [])
                  if isinstance(item, str) and item.strip()
              ]
              if not name or not observations:
                  continue
              quoted: List[str] = []
              for observation in observations[:MAX_OBSERVATIONS]:
                  snippet = " ".join(observation.split())
                  if len(snippet) > OBSERVATION_CHARS:
                      snippet = snippet[: OBSERVATION_CHARS - 1].rstrip() + "..."
                  quoted.append('"' + snippet + '"')
              line = "- " + name + ((" (" + kind + ")") if kind else "") + ": " + " ".join(quoted)
              if lines and used + len(line) > RECALL_CHARS:
                  break
              lines.append(line)
              used += len(line)
          if not lines:
              return "", 0
          header = "From the shared " + SERVER_NAME + " graph:"
          return header + "\n" + "\n".join(lines), len(lines)


      async def _search_graph_async(terms: Sequence[str], timeout: float) -> List[Dict[str, Any]]:
          """Union search_nodes hits for every term over one stateless MCP session."""

          async def _collect() -> List[Dict[str, Any]]:
              # Imported here so module import stays cheap and a missing SDK reads
              # as "recall unavailable", not as "plugin failed to load".
              from mcp.client.session import ClientSession
              from mcp.client.streamable_http import streamable_http_client

              found: Dict[str, Dict[str, Any]] = {}
              async with streamable_http_client(GRAPH_URL) as streams:
                  read_stream, write_stream = streams[0], streams[1]
                  async with ClientSession(read_stream, write_stream) as session:
                      await session.initialize()
                      for term in terms:
                          result = await session.call_tool("search_nodes", {"query": term})
                          if getattr(result, "isError", False) or getattr(result, "is_error", False):
                              continue
                          for block in result.content or []:
                              text = getattr(block, "text", None)
                              if not text:
                                  continue
                              try:
                                  payload = json.loads(text)
                              except ValueError:
                                  continue
                              for entity in payload.get("entities") or []:
                                  if isinstance(entity, dict) and entity.get("name"):
                                      found.setdefault(str(entity["name"]), entity)
              return list(found.values())

          return await asyncio.wait_for(_collect(), timeout=timeout)


      def _search_graph(terms: Sequence[str], timeout: float) -> List[Dict[str, Any]]:
          """Blocking wrapper; called from the manager's background/prefetch threads."""
          return asyncio.run(_search_graph_async(terms, timeout))


      class AgentMemoryProvider(MemoryProvider):
          """Recall from the shared graph, and nudge a review every NUDGE_TURNS turns."""

          def __init__(self) -> None:
              self._session_id = ""
              self._lock = threading.Lock()
              self._cache: Dict[str, Tuple[str, int]] = {}
              self._nudge_due = False
              self._last_count = 0
              self._warned = False

          # -- Identity -----------------------------------------------------------

          @property
          def name(self) -> str:
              return "agent-memory"

          def is_available(self) -> bool:
              # No network here: the loopback service is checked only when a search
              # actually runs (an unreachable graph degrades to "no recall").
              return GRAPH_URL.startswith("http://") or GRAPH_URL.startswith("https://")

          def unavailable_reason(self) -> str:
              return "GRAPH_URL was not interpolated at build time"

          # -- Lifecycle ----------------------------------------------------------

          def initialize(self, session_id: str, **kwargs) -> None:
              self._session_id = session_id or ""
              self._nudge_due = False
              self._last_count = 0

          def on_session_switch(
              self, new_session_id: str, *, parent_session_id: str = "", reset: bool = False,
              rewound: bool = False, **kwargs,
          ) -> None:
              with self._lock:
                  if reset:
                      self._cache.clear()
                  self._session_id = new_session_id or ""
              self._nudge_due = False
              self._last_count = 0

          def shutdown(self) -> None:
              self._cache.clear()

          # -- Prompt / recall ----------------------------------------------------

          def system_prompt_block(self) -> str:
              return (
                  "The shared `" + SERVER_NAME + "` MCP server is this host's persistent memory "
                  "(Hermes's native MEMORY.md store is off). Relevant entries are recalled into "
                  "context automatically before each turn, and a review note arrives every "
                  + str(NUDGE_TURNS) + " turns; save durable facts with that server's tools when "
                  "you learn them."
              )

          def on_turn_start(self, turn_number: int, message: str, **kwargs) -> None:
              self._last_count = 0
              self._nudge_due = bool(
                  NUDGE_TURNS > 0 and turn_number and turn_number % NUDGE_TURNS == 0
              )

          def queue_prefetch(self, query: str, *, session_id: str = "") -> None:
              """Warm the next turn's recall. Runs on the manager's background worker."""
              terms = _search_terms(query)
              if not terms:
                  return
              text, count = self._recall(terms, timeout=BACKGROUND_TIMEOUT_S)
              with self._lock:
                  self._cache[session_id or self._session_id] = (text, count)

          def prefetch(self, query: str, *, session_id: str = "") -> str:
              """Consume the queued recall (fallback: a short synchronous search)."""
              with self._lock:
                  cached = self._cache.pop(session_id or self._session_id, None)
              text, count = cached if cached is not None else ("", 0)
              if not text:
                  terms = _search_terms(query)
                  if terms:
                      text, count = self._recall(terms, timeout=PREFETCH_TIMEOUT_S)
              self._last_count = count
              parts: List[str] = []
              if text:
                  parts.append(text)
              if self._nudge_due:
                  self._nudge_due = False
                  parts.append(REVIEW_NOTE)
              return "\n\n".join(parts)

          def recall_status(self) -> Optional[RecallStatus]:
              if self._last_count <= 0:
                  return None
              return RecallStatus(provider_label=self.name, count=self._last_count)

          # -- No tools: writes stay on the MCP surface ---------------------------

          def get_tool_schemas(self) -> List[Dict[str, Any]]:
              return []

          def handle_tool_call(self, tool_name: str, args: Dict[str, Any], **kwargs) -> str:
              raise NotImplementedError("agent-memory publishes no tools")

          # -- Internals ----------------------------------------------------------

          def _recall(self, terms: Sequence[str], *, timeout: float) -> Tuple[str, int]:
              try:
                  entities = _search_graph(terms, timeout)
              except Exception as error:  # offline proxy, SDK error, timeout: never block a turn
                  if not self._warned:
                      self._warned = True
                      logger.warning(
                          "agent-memory: recall unavailable at %s: %s", GRAPH_URL, error
                      )
                  else:
                      logger.debug("agent-memory: recall failed: %s", error, exc_info=True)
                  return "", 0
              return _format_recall(entities)


      def register(ctx) -> None:
          """Entry point for hermes_agent.memory_providers."""
          ctx.register_memory_provider(AgentMemoryProvider())


      __all__ = ["AgentMemoryProvider", "register"]
    '';
  };

  pyproject = pkgs.writeTextFile {
    name = "hermes-agent-memory-pyproject.toml";
    text = ''
      [build-system]
      requires = [ "setuptools" ]
      build-backend = "setuptools.build_meta"

      [project]
      name = "hermes-agent-memory"
      version = "0.1.0"
      description = "Hermes memory provider for the shared agent-memory knowledge graph"
      requires-python = ">=3.12"

      [project.entry-points."hermes_agent.memory_providers"]
      ${providerName} = "agent_memory_provider:register"

      [tool.setuptools]
      packages = [ "agent_memory_provider" ]
    '';
  };
in
{
  # `memory.provider` in home/hermes.nix must match this name, which is how
  # the entry point is keyed too.
  name = providerName;

  # Interpreter-pinned on purpose: the module type-checks extraPythonPackages
  # against the hermes venv (python312, nix/hermes-agent.nix), so a
  # default-python build would be rejected at activation.
  package = pkgs.python312Packages.buildPythonPackage {
    pname = "hermes-agent-memory";
    version = "0.1.0";
    pyproject = true;
    src = pkgs.runCommand "hermes-agent-memory-src" { } ''
      mkdir -p $out/agent_memory_provider
      install -m 0444 ${providerModule} $out/agent_memory_provider/__init__.py
      install -m 0444 ${pyproject} $out/pyproject.toml
      # Build-time syntax gate. The interpreter's import check is not usable
      # here: the module subclasses agent.memory_provider, which exists only
      # inside the Hermes venv, not in a build sandbox.
      ${pkgs.python312}/bin/python3 -m py_compile $out/agent_memory_provider/__init__.py
      rm -rf $out/agent_memory_provider/__pycache__
    '';
    build-system = [ pkgs.python312Packages.setuptools ];
    # No test suite travels with the module; the gate above is the build-time
    # check, and the runtime behaviour is exercised against the real venv.
    doCheck = false;
    meta = {
      description = "Hermes memory provider for the shared agent-memory knowledge graph";
      platforms = pkgs.lib.platforms.unix;
    };
  };
}
