_: {
  preservation = {
    enable = true;
    preserveAt."/persistent" = {
      commonMountOptions = [
        "x-gvfs-hide"
      ];
      files = [
        {
          file = "/etc/machine-id";
          inInitrd = true;
        }
      ];
      directories = [
        {
          directory = "/var/cache/ccache";
          user = "root";
          group = "nixbld";
        }
        {
          directory = "/etc/NetworkManager/system-connections";
        }
        {
          directory = "/etc/opt/ivpn";
        }
        "/var/lib/OpenRGB"
        "/var/lib/transmission"
        {
          directory = "/var/lib/lidarr";
          user = "codebam";
          group = "users";
        }
        "/var/lib/navidrome"
        "/var/lib/private/prowlarr"
        "/var/lib/bluetooth"
        "/var/lib/iwd"
        "/var/lib/nixos"
        # Root is wiped at boot, so without this every `flatpak install` --
        # runtimes, apps, and the flathub remote itself -- is undone by the
        # next reboot. The per-user half is under codebam below.
        "/var/lib/flatpak"
        "/var/lib/sbctl"
        "/var/lib/systemd/coredump"
        "/var/lib/tailscale"
        "/var/log"
        {
          directory = "/var/lib/colord";
          user = "colord";
          group = "colord";
          mode = "0700";
        }
        {
          directory = "/var/lib/private/ollama";
          user = "ollama";
          group = "ollama";
        }
        {
          directory = "/var/lib/acme";
          user = "acme";
          group = "nginx";
        }
      ];
      users = {
        root = {
          directories = [
            {
              directory = ".ssh";
              mode = "0700";
            }
          ];
        };
        codebam = {
          commonMountOptions = [
            "x-gvfs-hide"
          ];
          files = [
            ".claude.json"
            ".config/kwinoutputconfig.json"
            ".config/kwalletrc"
            ".config/kwalletmanagerrc"
            ".config/viewport/openai-auth.json"
          ];
          directories = [
            {
              directory = ".ssh";
              mode = "0700";
            }
            {
              directory = ".gnupg";
              mode = "0700";
            }
            {
              directory = ".nixops";
              mode = "0700";
            }
            {
              directory = ".local/share/keyrings";
              mode = "0700";
            }
            "Downloads"
            "Music"
            "Pictures"
            "Documents"
            "Videos"
            "Games"
            ".local/share/direnv"
            ".local/share/fish"
            # OpenCode sessions, auth, snapshots, selected model, prompt
            # history, and mutable global plugin/config state.
            ".local/share/opencode"
            ".local/state/opencode"
            ".config/opencode"
            # `flatpak --user install` and the app data those apps write.
            # The system-wide half is /var/lib/flatpak above.
            ".local/share/flatpak"
            ".var"
            ".steam"
            ".tmux"
            ".local/share/Steam"
            ".claude"
            ".config/claude"
            ".config/claude-code"
            ".gemini"
            ".kimi-code"
            ".librewolf"
            ".firedragon"
            ".password-store"
            ".local/state/wireplumber"
            ".local/state/mpv"
            ".config/mprisence"
            ".config/Antigravity"
            ".config/vesktop"
            ".config/equibop"
            ".config/Element"
            ".config/discord"
            ".config/discordcanary"
            ".config/discordptb"
            ".config/in.cinny.app"
            ".local/share/TelegramDesktop"
            ".local/share/bolt-launcher"
            ".local/share/zoxide"
            ".config/YouTube Music Desktop App"
            ".config/mnw"
            ".local/share/PrismLauncher"
            ".local/share/mnw"
            ".local/share/containers"
            ".config/OpenRGB"
            # obs-studio scenes, profiles and the plugin settings under
            # plugin_config; nothing in it is generated by the home-manager
            # module, so a root wipe loses every scene collection.
            ".config/obs-studio"
            ".config/heroic"
            ".config/nushell"
            ".config/qmk"
            ".cache/nix-index"
            ".config/github-copilot"
            # hermes-desktop CEF user-data (window-state, theme, preferences,
            # desktop-installation.json). HERMES_HOME itself is preserved above
            # via /var/lib/hermes in desktop/configuration/preservation.nix.
            ".config/Hermes"
            {
              directory = ".config/gh";
              mode = "0700";
            }
            ".config/gcloud"
            ".config/supersonic"
            ".config/feishin"
            ".local/share/steel"
            ".config/calcurse"
            ".local/share/calcurse"
            ".config/retroarch"
            ".config/chromium"
            ".config/mozilla"
            ".config/google-chrome"
            ".config/google-chrome-unstable"
            ".config/agy-sandbox"
            ".local/share/vkBasalt/shaders"
            ".local/share/kwalletd"
            ".local/share/iamb"
            ".cache/iamb"
            ".local/share/uv"
            ".local/bin"
            # SigmaShake Desktop: license, prefs, daemon state. Not generated
            # by the flake; a root wipe would drop the login.
            ".sigmashake"
          ];
        };
      };
    };
  };

  systemd.tmpfiles.settings.preservation = {
    "/home/codebam/Videos/Anime".d = {
      user = "codebam";
      group = "users";
      mode = "0755";
    };
    # Only Pictures itself is preserved; grim writes into this subdirectory and
    # fails silently if it is missing after a root wipe.
    "/home/codebam/Pictures/Screenshots".d = {
      user = "codebam";
      group = "users";
      mode = "0755";
    };
  };

  systemd.services.systemd-machine-id-commit = {
    unitConfig.ConditionPathIsMountPoint = [
      ""
      "/persistent/etc/machine-id"
    ];
    serviceConfig.ExecStart = [
      ""
      "systemd-machine-id-setup --commit --root /persistent"
    ];
  };
}
